package view;


public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipalView
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        menu1 = new com.raven.menu.Menu();
        jLabel1 = new javax.swing.JLabel();
        menuItem1 = new com.raven.menu.MenuItem();
        menuItem2 = new com.raven.menu.MenuItem();
        menuItem3 = new com.raven.menu.MenuItem();
        menuItem4 = new com.raven.menu.MenuItem();
        menuItem5 = new com.raven.menu.MenuItem();
        menuItem6 = new com.raven.menu.MenuItem();
        subMenuPanel1 = new com.raven.menu.SubMenuPanel();
        pnlRight = new javax.swing.JPanel();
        dpnViews = new javax.swing.JDesktopPane();
        tfTyUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(38, 38, 38));

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));

        pnlLeft.setBackground(new java.awt.Color(68, 63, 65,0));
        pnlLeft.setOpaque(false);

        menu1.setBackground(new java.awt.Color(80, 80, 80));
        menu1.setForeground(new java.awt.Color(80, 80, 80));
        menu1.setSubMenuPanel(subMenuPanel1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));
        menu1.add(jLabel1);

        menuItem1.setBackground(new java.awt.Color(2, 166, 166));
        menuItem1.setForeground(new java.awt.Color(2, 166, 166));
        menuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/House_Icon.png"))); // NOI18N
        menuItem1.setText("menuItem1");
        menuItem1.setFont(new java.awt.Font("Poppins Light", 0, 20)); // NOI18N
        menuItem1.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "images/View_Icon.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem1.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "About Us" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem1.setPreferredSize(new java.awt.Dimension(70, 70));
        menu1.add(menuItem1);

        menuItem2.setBackground(new java.awt.Color(2, 166, 166));
        menuItem2.setForeground(new java.awt.Color(2, 166, 166));
        menuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Icon.png"))); // NOI18N
        menuItem2.setText("menuItem2");
        menuItem2.setFont(new java.awt.Font("Poppins Light", 0, 20)); // NOI18N
        menuItem2.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "images/Add_Icon.png", "images/Add_Icon.png", "images/Add_Icon.png", "images/Manage_Icon.png", "images/Manage_Icon.png", "images/Manage_Icon.png", "images/Manage_Icon.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem2.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Add User", "Add client", "Add employee", "Manage User", "Manage client", "Manage employee", "User history" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem2.setPreferredSize(new java.awt.Dimension(70, 70));
        menu1.add(menuItem2);

        menuItem3.setBackground(new java.awt.Color(2, 166, 166));
        menuItem3.setForeground(new java.awt.Color(2, 166, 166));
        menuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Book_Icon.png"))); // NOI18N
        menuItem3.setText("menuItem3");
        menuItem3.setFont(new java.awt.Font("Poppins Light", 0, 20)); // NOI18N
        menuItem3.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "images/Add_Icon.png", "images/Add_Icon.png", "images/Manage_Icon.png", "images/Manage_Icon.png", "images/Manage_Icon.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem3.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Add book", "Add category", "Manage book", "Manage category", "inventory history" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem3.setPreferredSize(new java.awt.Dimension(70, 70));
        menu1.add(menuItem3);

        menuItem4.setBackground(new java.awt.Color(2, 166, 166));
        menuItem4.setForeground(new java.awt.Color(2, 166, 166));
        menuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Loan_Icon.png"))); // NOI18N
        menuItem4.setText("menuItem4");
        menuItem4.setFont(new java.awt.Font("Poppins Light", 0, 20)); // NOI18N
        menuItem4.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "images/Remove_Icon.png", "images/Manage_Icon.png", "images/Manage_Icon.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem4.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Apply loan", "Manage return", "Circulation history" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem4.setPreferredSize(new java.awt.Dimension(70, 70));
        menu1.add(menuItem4);

        menuItem5.setBackground(new java.awt.Color(2, 166, 166));
        menuItem5.setForeground(new java.awt.Color(2, 166, 166));
        menuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Report_Icon.png"))); // NOI18N
        menuItem5.setText("menuItem5");
        menuItem5.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "images/DownloadReport_Icon.png", "images/DownloadReport_Icon.png", "images/DownloadReport_Icon.png", "images/DownloadReport_Icon.png", "images/DownloadReport_Icon.png", "images/DownloadReport_Icon.png", "images/DownloadReport_Icon.png", "images/DownloadReport_Icon.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem5.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Manage client", "Manage employee", "User history", "Manage book", "Manage category", "Inventory history", "Manage return", "circulation history" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem5.setPreferredSize(new java.awt.Dimension(70, 70));
        menu1.add(menuItem5);

        menuItem6.setBackground(new java.awt.Color(2, 166, 166));
        menuItem6.setForeground(new java.awt.Color(2, 166, 166));
        menuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit_Icon.png"))); // NOI18N
        menuItem6.setText("menuItem6");
        menuItem6.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "images/Change_Icon.png", "images/TinyExit_Icon.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem6.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Change account", "Exit program" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem6.setPreferredSize(new java.awt.Dimension(70, 70));
        menu1.add(menuItem6);

        subMenuPanel1.setBackground(new java.awt.Color(60, 63, 65));
        subMenuPanel1.setForeground(new java.awt.Color(65, 65, 65));
        subMenuPanel1.setFont(new java.awt.Font("Poppins Light", 0, 50)); // NOI18N
        subMenuPanel1.setOpacity(1.0F);
        subMenuPanel1.setOpaque(true);
        subMenuPanel1.setPreferredSize(new java.awt.Dimension(10, 35));
        subMenuPanel1.setRound(0);

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(subMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
            .addComponent(subMenuPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlRight.setOpaque(false);

        dpnViews.setOpaque(false);

        tfTyUser.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        tfTyUser.setForeground(new java.awt.Color(62, 67, 76));
        tfTyUser.setText("0");

        dpnViews.setLayer(tfTyUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpnViewsLayout = new javax.swing.GroupLayout(dpnViews);
        dpnViews.setLayout(dpnViewsLayout);
        dpnViewsLayout.setHorizontalGroup(
            dpnViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnViewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfTyUser, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        dpnViewsLayout.setVerticalGroup(
            dpnViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnViewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfTyUser, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnViews)
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnViews)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(38, 38, 38));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle_Icon.png"))); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle_Icon.png"))); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle_Icon.png"))); // NOI18N
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane dpnViews;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public com.raven.menu.Menu menu1;
    private com.raven.menu.MenuItem menuItem1;
    public com.raven.menu.MenuItem menuItem2;
    private com.raven.menu.MenuItem menuItem3;
    private com.raven.menu.MenuItem menuItem4;
    private com.raven.menu.MenuItem menuItem5;
    private com.raven.menu.MenuItem menuItem6;
    private javax.swing.JPanel pnlLeft;
    public javax.swing.JPanel pnlRight;
    public com.raven.menu.SubMenuPanel subMenuPanel1;
    public javax.swing.JLabel tfTyUser;
    // End of variables declaration//GEN-END:variables
}
