package view;


public class IFrmEmployee extends javax.swing.JInternalFrame {

    public IFrmEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlFlieds = new javax.swing.JPanel();
        tfINDI = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfAdress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dcBirthdate = new com.toedter.calendar.JDateChooser();
        tfPhoneNumber = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        cmbSex = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbWorkPosition = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        tfSalary = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dcIntegration = new com.toedter.calendar.JDateChooser();
        cmbState = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 760, 10));

        btnRegister.setBackground(new java.awt.Color(2, 166, 166));
        btnRegister.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.setPreferredSize(new java.awt.Dimension(240, 43));
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        jLabel2.setText("Add new employee");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pnlFlieds.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfINDI.setBackground(new java.awt.Color(6, 6, 6));
        tfINDI.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfINDI.setForeground(new java.awt.Color(255, 255, 255));
        tfINDI.setToolTipText("NIP");
        tfINDI.setBorder(null);
        tfINDI.setName(""); // NOI18N
        tfINDI.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlFlieds.add(tfINDI, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 61, 210, -1));

        jLabel12.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel12.setText("NDI");
        pnlFlieds.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 41, -1, -1));

        tfAdress.setBackground(new java.awt.Color(6, 6, 6));
        tfAdress.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfAdress.setForeground(new java.awt.Color(255, 255, 255));
        tfAdress.setToolTipText("adress");
        tfAdress.setBorder(null);
        tfAdress.setName(""); // NOI18N
        tfAdress.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlFlieds.add(tfAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 220, -1));

        jLabel5.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel5.setText("Address");
        pnlFlieds.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel6.setText("Phone number");
        pnlFlieds.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel4.setText("birthdate");
        pnlFlieds.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        dcBirthdate.setPreferredSize(new java.awt.Dimension(85, 36));
        pnlFlieds.add(dcBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 220, -1));

        tfPhoneNumber.setBackground(new java.awt.Color(6, 6, 6));
        tfPhoneNumber.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        tfPhoneNumber.setToolTipText("");
        tfPhoneNumber.setBorder(null);
        tfPhoneNumber.setName(""); // NOI18N
        tfPhoneNumber.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlFlieds.add(tfPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 220, -1));

        tfName.setBackground(new java.awt.Color(6, 6, 6));
        tfName.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        tfName.setToolTipText("");
        tfName.setBorder(null);
        tfName.setName(""); // NOI18N
        tfName.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlFlieds.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 61, 220, -1));

        cmbSex.setToolTipText("sex");
        cmbSex.setPreferredSize(new java.awt.Dimension(72, 36));
        pnlFlieds.add(cmbSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 220, -1));

        jLabel13.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel13.setText("Sex");
        pnlFlieds.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel14.setText("Work Position");
        pnlFlieds.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        cmbWorkPosition.setToolTipText("sex");
        cmbWorkPosition.setPreferredSize(new java.awt.Dimension(72, 36));
        pnlFlieds.add(cmbWorkPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 220, -1));

        jLabel15.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel15.setText("Salary");
        pnlFlieds.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        tfSalary.setBackground(new java.awt.Color(6, 6, 6));
        tfSalary.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfSalary.setForeground(new java.awt.Color(255, 255, 255));
        tfSalary.setToolTipText("salary");
        tfSalary.setBorder(null);
        tfSalary.setName(""); // NOI18N
        tfSalary.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlFlieds.add(tfSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 220, -1));

        jLabel16.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel16.setText("Integration ");
        pnlFlieds.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        dcIntegration.setPreferredSize(new java.awt.Dimension(85, 36));
        pnlFlieds.add(dcIntegration, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 220, -1));

        cmbState.setToolTipText("state of user");
        cmbState.setPreferredSize(new java.awt.Dimension(72, 36));
        pnlFlieds.add(cmbState, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 180, -1));

        jLabel17.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel17.setText("State");
        pnlFlieds.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel1.setText("Name");
        pnlFlieds.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        getContentPane().add(pnlFlieds, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 790, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegister;
    public javax.swing.JComboBox<String> cmbSex;
    public javax.swing.JComboBox<String> cmbState;
    public javax.swing.JComboBox<String> cmbWorkPosition;
    public com.toedter.calendar.JDateChooser dcBirthdate;
    public com.toedter.calendar.JDateChooser dcIntegration;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JPanel pnlFlieds;
    public javax.swing.JTextField tfAdress;
    public javax.swing.JTextField tfINDI;
    public javax.swing.JTextField tfName;
    public javax.swing.JTextField tfPhoneNumber;
    public javax.swing.JTextField tfSalary;
    // End of variables declaration//GEN-END:variables
}
