package view;


public class IFrmClient extends javax.swing.JInternalFrame {


    public IFrmClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        tfName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfFatherLastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMotherLastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDomicile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfPhoneNumber = new javax.swing.JTextField();
        cmbEstate = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfName.setBackground(new java.awt.Color(6, 6, 6));
        tfName.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        tfName.setToolTipText("name");
        tfName.setBorder(null);
        tfName.setName(""); // NOI18N
        tfName.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlPrincipal.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 210, -1));

        jLabel1.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel1.setText("Name");
        pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        pnlPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 510, 10));

        btnRegister.setBackground(new java.awt.Color(2, 166, 166));
        btnRegister.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.setPreferredSize(new java.awt.Dimension(240, 43));
        pnlPrincipal.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        jLabel2.setText("Add new client");
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel3.setText("Father's last name");
        pnlPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        tfFatherLastname.setBackground(new java.awt.Color(6, 6, 6));
        tfFatherLastname.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfFatherLastname.setForeground(new java.awt.Color(255, 255, 255));
        tfFatherLastname.setToolTipText("father name");
        tfFatherLastname.setBorder(null);
        tfFatherLastname.setName(""); // NOI18N
        tfFatherLastname.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlPrincipal.add(tfFatherLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 210, -1));

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel4.setText("Estate");
        pnlPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        tfMotherLastname.setBackground(new java.awt.Color(6, 6, 6));
        tfMotherLastname.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfMotherLastname.setForeground(new java.awt.Color(255, 255, 255));
        tfMotherLastname.setToolTipText("mother name");
        tfMotherLastname.setBorder(null);
        tfMotherLastname.setName(""); // NOI18N
        tfMotherLastname.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlPrincipal.add(tfMotherLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 210, -1));

        jLabel5.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel5.setText("Domicile");
        pnlPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        tfDomicile.setBackground(new java.awt.Color(6, 6, 6));
        tfDomicile.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfDomicile.setForeground(new java.awt.Color(255, 255, 255));
        tfDomicile.setToolTipText("domicile");
        tfDomicile.setBorder(null);
        tfDomicile.setName(""); // NOI18N
        tfDomicile.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlPrincipal.add(tfDomicile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 220, -1));

        jLabel6.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel6.setText("Phone number");
        pnlPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        tfPhoneNumber.setBackground(new java.awt.Color(6, 6, 6));
        tfPhoneNumber.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        tfPhoneNumber.setToolTipText("phone number");
        tfPhoneNumber.setBorder(null);
        tfPhoneNumber.setName(""); // NOI18N
        tfPhoneNumber.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlPrincipal.add(tfPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 220, -1));

        cmbEstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));
        cmbEstate.setPreferredSize(new java.awt.Dimension(72, 36));
        pnlPrincipal.add(cmbEstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 220, -1));

        jLabel7.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel7.setText("Mother's last name  ");
        pnlPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegister;
    public javax.swing.JComboBox<String> cmbEstate;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JPanel pnlPrincipal;
    public javax.swing.JTextField tfDomicile;
    public javax.swing.JTextField tfFatherLastname;
    public javax.swing.JTextField tfMotherLastname;
    public javax.swing.JTextField tfName;
    public javax.swing.JTextField tfPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
