package view;


public class IFrmManageEmployee extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmManageClient
     */
    public IFrmManageEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        pnlFlieds = new javax.swing.JPanel();
        tfNDI = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfAdress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dcBirthdate = new com.toedter.calendar.JDateChooser();
        tfPhoneNumber = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        cmbSex = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbWorkPosition = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        tfSalary = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dcIntegration = new com.toedter.calendar.JDateChooser();
        cmbState = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search_Icon.png"))); // NOI18N
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 30, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1020, 10));

        btnUpdate.setBackground(new java.awt.Color(2, 166, 166));
        btnUpdate.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.setPreferredSize(new java.awt.Dimension(240, 43));
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 170, 40));

        btnDelete.setBackground(new java.awt.Color(166, 2, 2));
        btnDelete.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.setPreferredSize(new java.awt.Dimension(240, 43));
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 180, 40));

        tfSearch.setBackground(new java.awt.Color(6, 6, 6));
        tfSearch.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfSearch.setForeground(new java.awt.Color(255, 255, 255));
        tfSearch.setToolTipText("");
        tfSearch.setBorder(null);
        tfSearch.setName(""); // NOI18N
        tfSearch.setPreferredSize(new java.awt.Dimension(250, 36));
        getContentPane().add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 160, 40));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        jLabel3.setText("Mange employee");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEmployee);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1030, 260));

        pnlFlieds.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfNDI.setBackground(new java.awt.Color(6, 6, 6));
        tfNDI.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfNDI.setForeground(new java.awt.Color(255, 255, 255));
        tfNDI.setToolTipText("NIP");
        tfNDI.setBorder(null);
        tfNDI.setName(""); // NOI18N
        tfNDI.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlFlieds.add(tfNDI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 210, -1));

        jLabel12.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel12.setText("NDI");
        pnlFlieds.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        tfAdress.setBackground(new java.awt.Color(6, 6, 6));
        tfAdress.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfAdress.setForeground(new java.awt.Color(255, 255, 255));
        tfAdress.setToolTipText("adress");
        tfAdress.setBorder(null);
        tfAdress.setName(""); // NOI18N
        tfAdress.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlFlieds.add(tfAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 220, -1));

        jLabel5.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel5.setText("Address");
        pnlFlieds.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel6.setText("Phone number");
        pnlFlieds.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel4.setText("birthdate");
        pnlFlieds.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        dcBirthdate.setPreferredSize(new java.awt.Dimension(85, 36));
        pnlFlieds.add(dcBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 220, -1));

        tfPhoneNumber.setBackground(new java.awt.Color(6, 6, 6));
        tfPhoneNumber.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        tfPhoneNumber.setToolTipText("");
        tfPhoneNumber.setBorder(null);
        tfPhoneNumber.setName(""); // NOI18N
        tfPhoneNumber.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlFlieds.add(tfPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 220, -1));

        tfName.setBackground(new java.awt.Color(6, 6, 6));
        tfName.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        tfName.setToolTipText("");
        tfName.setBorder(null);
        tfName.setName(""); // NOI18N
        tfName.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlFlieds.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 220, -1));

        cmbSex.setToolTipText("sex");
        cmbSex.setPreferredSize(new java.awt.Dimension(72, 36));
        pnlFlieds.add(cmbSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 220, -1));

        jLabel13.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel13.setText("Sex");
        pnlFlieds.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel14.setText("Work Position");
        pnlFlieds.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        cmbWorkPosition.setToolTipText("sex");
        cmbWorkPosition.setPreferredSize(new java.awt.Dimension(72, 36));
        pnlFlieds.add(cmbWorkPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 220, -1));

        jLabel15.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel15.setText("Salary");
        pnlFlieds.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        tfSalary.setBackground(new java.awt.Color(6, 6, 6));
        tfSalary.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfSalary.setForeground(new java.awt.Color(255, 255, 255));
        tfSalary.setToolTipText("salary");
        tfSalary.setBorder(null);
        tfSalary.setName(""); // NOI18N
        tfSalary.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlFlieds.add(tfSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 220, -1));

        jLabel16.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel16.setText("Integration ");
        pnlFlieds.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        dcIntegration.setPreferredSize(new java.awt.Dimension(85, 36));
        pnlFlieds.add(dcIntegration, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 220, -1));

        cmbState.setToolTipText("state of user");
        cmbState.setPreferredSize(new java.awt.Dimension(72, 36));
        pnlFlieds.add(cmbState, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 180, -1));

        jLabel17.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel17.setText("State");
        pnlFlieds.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel1.setText("Name");
        pnlFlieds.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        getContentPane().add(pnlFlieds, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1060, 320));

        jMenu1.setText("Generate");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DownloadReport_Icon.png"))); // NOI18N
        jMenuItem1.setText("Report");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDelete;
    public javax.swing.JLabel btnSearch;
    public javax.swing.JButton btnUpdate;
    public javax.swing.JComboBox<String> cmbSex;
    public javax.swing.JComboBox<String> cmbState;
    public javax.swing.JComboBox<String> cmbWorkPosition;
    public com.toedter.calendar.JDateChooser dcBirthdate;
    public com.toedter.calendar.JDateChooser dcIntegration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JPanel pnlFlieds;
    public javax.swing.JTable tblEmployee;
    public javax.swing.JTextField tfAdress;
    public javax.swing.JTextField tfNDI;
    public javax.swing.JTextField tfName;
    public javax.swing.JTextField tfPhoneNumber;
    public javax.swing.JTextField tfSalary;
    public javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
