package view;


public class IFrmUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmClient
     */
    public IFrmUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        tfUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUserPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfUserEmail = new javax.swing.JTextField();
        cmbLevelAccess = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUserName.setBackground(new java.awt.Color(6, 6, 6));
        tfUserName.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfUserName.setForeground(new java.awt.Color(255, 255, 255));
        tfUserName.setToolTipText("user name");
        tfUserName.setBorder(null);
        tfUserName.setName(""); // NOI18N
        tfUserName.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlPrincipal.add(tfUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 210, -1));

        jLabel1.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel1.setText("User name");
        pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        pnlPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 510, 10));

        btnRegister.setBackground(new java.awt.Color(2, 166, 166));
        btnRegister.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.setPreferredSize(new java.awt.Dimension(240, 43));
        pnlPrincipal.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        jLabel2.setText("Add new user");
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel3.setText("User Password");
        pnlPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        tfUserPassword.setBackground(new java.awt.Color(6, 6, 6));
        tfUserPassword.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfUserPassword.setForeground(new java.awt.Color(255, 255, 255));
        tfUserPassword.setToolTipText("user password");
        tfUserPassword.setBorder(null);
        tfUserPassword.setName(""); // NOI18N
        tfUserPassword.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlPrincipal.add(tfUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 210, -1));

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel4.setText("Level Acces");
        pnlPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel5.setText("User Email");
        pnlPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        tfUserEmail.setBackground(new java.awt.Color(6, 6, 6));
        tfUserEmail.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfUserEmail.setForeground(new java.awt.Color(255, 255, 255));
        tfUserEmail.setToolTipText("email");
        tfUserEmail.setBorder(null);
        tfUserEmail.setName(""); // NOI18N
        tfUserEmail.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlPrincipal.add(tfUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 220, -1));

        cmbLevelAccess.setToolTipText("level of access");
        cmbLevelAccess.setPreferredSize(new java.awt.Dimension(72, 36));
        pnlPrincipal.add(cmbLevelAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 220, -1));

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegister;
    public javax.swing.JComboBox<String> cmbLevelAccess;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JPanel pnlPrincipal;
    public javax.swing.JTextField tfUserEmail;
    public javax.swing.JTextField tfUserName;
    public javax.swing.JTextField tfUserPassword;
    // End of variables declaration//GEN-END:variables
}
