/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author usuario
 */
public class IFrmBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmClient
     */
    public IFrmBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfISBN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        tfAuthor = new javax.swing.JTextField();
        dcPublicationDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        Author = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfPages = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfDescription = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfNumberOfCopies = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbEdition = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cmbLanguaje = new javax.swing.JComboBox<>();
        Languaje = new javax.swing.JLabel();
        cmbIdStATE = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 700, 10));

        btnAdd.setBackground(new java.awt.Color(2, 166, 166));
        btnAdd.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.setPreferredSize(new java.awt.Dimension(240, 43));
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        jLabel2.setText("Add new book");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfISBN.setBackground(new java.awt.Color(6, 6, 6));
        tfISBN.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfISBN.setForeground(new java.awt.Color(255, 255, 255));
        tfISBN.setToolTipText("");
        tfISBN.setBorder(null);
        tfISBN.setName(""); // NOI18N
        tfISBN.setPreferredSize(new java.awt.Dimension(250, 36));
        jPanel1.add(tfISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 180, -1));

        jLabel1.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel1.setText("ISBN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel3.setText("Title");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        tfTitle.setBackground(new java.awt.Color(6, 6, 6));
        tfTitle.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfTitle.setForeground(new java.awt.Color(255, 255, 255));
        tfTitle.setToolTipText("");
        tfTitle.setBorder(null);
        tfTitle.setName(""); // NOI18N
        tfTitle.setPreferredSize(new java.awt.Dimension(250, 36));
        jPanel1.add(tfTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 180, -1));

        tfAuthor.setBackground(new java.awt.Color(6, 6, 6));
        tfAuthor.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfAuthor.setForeground(new java.awt.Color(255, 255, 255));
        tfAuthor.setToolTipText("");
        tfAuthor.setBorder(null);
        tfAuthor.setName(""); // NOI18N
        tfAuthor.setPreferredSize(new java.awt.Dimension(250, 36));
        jPanel1.add(tfAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 180, -1));

        dcPublicationDate.setPreferredSize(new java.awt.Dimension(85, 36));
        jPanel1.add(dcPublicationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 180, -1));

        jLabel9.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel9.setText("Publication date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Author.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        Author.setText("Author");
        jPanel1.add(Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel8.setText("Pages");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        tfPages.setBackground(new java.awt.Color(6, 6, 6));
        tfPages.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfPages.setForeground(new java.awt.Color(255, 255, 255));
        tfPages.setToolTipText("");
        tfPages.setBorder(null);
        tfPages.setName(""); // NOI18N
        tfPages.setPreferredSize(new java.awt.Dimension(250, 36));
        jPanel1.add(tfPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 180, -1));

        jLabel10.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel10.setText("Description");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        tfDescription.setBackground(new java.awt.Color(6, 6, 6));
        tfDescription.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfDescription.setForeground(new java.awt.Color(255, 255, 255));
        tfDescription.setToolTipText("");
        tfDescription.setBorder(null);
        tfDescription.setName(""); // NOI18N
        tfDescription.setPreferredSize(new java.awt.Dimension(250, 36));
        jPanel1.add(tfDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 180, -1));

        jLabel11.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel11.setText("Number of copies");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        tfNumberOfCopies.setBackground(new java.awt.Color(6, 6, 6));
        tfNumberOfCopies.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfNumberOfCopies.setForeground(new java.awt.Color(255, 255, 255));
        tfNumberOfCopies.setToolTipText("");
        tfNumberOfCopies.setBorder(null);
        tfNumberOfCopies.setName(""); // NOI18N
        tfNumberOfCopies.setPreferredSize(new java.awt.Dimension(250, 36));
        jPanel1.add(tfNumberOfCopies, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 180, -1));

        jLabel12.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel12.setText("Estate");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        cmbCategory.setToolTipText("sex");
        cmbCategory.setPreferredSize(new java.awt.Dimension(72, 36));
        jPanel1.add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 180, -1));

        jLabel14.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel14.setText("Category");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        cmbEdition.setToolTipText("sex");
        cmbEdition.setPreferredSize(new java.awt.Dimension(72, 36));
        jPanel1.add(cmbEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 180, -1));

        jLabel15.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel15.setText("Edition");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        cmbLanguaje.setToolTipText("sex");
        cmbLanguaje.setPreferredSize(new java.awt.Dimension(72, 36));
        jPanel1.add(cmbLanguaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 180, -1));

        Languaje.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        Languaje.setText("Languaje");
        jPanel1.add(Languaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        cmbIdStATE.setToolTipText("sex");
        cmbIdStATE.setPreferredSize(new java.awt.Dimension(72, 36));
        jPanel1.add(cmbIdStATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 690, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Author;
    public javax.swing.JLabel Languaje;
    public javax.swing.JButton btnAdd;
    public javax.swing.JComboBox<String> cmbCategory;
    public javax.swing.JComboBox<String> cmbEdition;
    public javax.swing.JComboBox<String> cmbIdStATE;
    public javax.swing.JComboBox<String> cmbLanguaje;
    public com.toedter.calendar.JDateChooser dcPublicationDate;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField tfAuthor;
    public javax.swing.JTextField tfDescription;
    public javax.swing.JTextField tfISBN;
    public javax.swing.JTextField tfNumberOfCopies;
    public javax.swing.JTextField tfPages;
    public javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables
}
