package view;


public class IFrmManageClient extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmManageClient
     */
    public IFrmManageClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        tfName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDomicile1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfFatherLastname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfMotherLastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfPhoneNumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbEstate = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tfMonetaryPenalty = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search_Icon.png"))); // NOI18N
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 30, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 790, 10));

        btnUpdate.setBackground(new java.awt.Color(2, 166, 166));
        btnUpdate.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.setPreferredSize(new java.awt.Dimension(240, 43));
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 170, 40));

        btnDelete.setBackground(new java.awt.Color(166, 2, 2));
        btnDelete.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.setPreferredSize(new java.awt.Dimension(240, 43));
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 180, 40));

        tfSearch.setBackground(new java.awt.Color(6, 6, 6));
        tfSearch.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfSearch.setForeground(new java.awt.Color(255, 255, 255));
        tfSearch.setToolTipText("");
        tfSearch.setBorder(null);
        tfSearch.setName(""); // NOI18N
        tfSearch.setPreferredSize(new java.awt.Dimension(250, 36));
        getContentPane().add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 160, 40));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        jLabel3.setText("Mange client");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblClient);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 790, 260));

        tfName.setBackground(new java.awt.Color(6, 6, 6));
        tfName.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        tfName.setToolTipText("");
        tfName.setBorder(null);
        tfName.setName(""); // NOI18N
        tfName.setPreferredSize(new java.awt.Dimension(250, 36));
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 210, -1));

        jLabel1.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel5.setText("Domicile");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        tfDomicile1.setBackground(new java.awt.Color(6, 6, 6));
        tfDomicile1.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfDomicile1.setForeground(new java.awt.Color(255, 255, 255));
        tfDomicile1.setToolTipText("");
        tfDomicile1.setBorder(null);
        tfDomicile1.setName(""); // NOI18N
        tfDomicile1.setPreferredSize(new java.awt.Dimension(250, 36));
        getContentPane().add(tfDomicile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 220, -1));

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel4.setText("Father's last name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        tfFatherLastname.setBackground(new java.awt.Color(6, 6, 6));
        tfFatherLastname.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfFatherLastname.setForeground(new java.awt.Color(255, 255, 255));
        tfFatherLastname.setToolTipText("");
        tfFatherLastname.setBorder(null);
        tfFatherLastname.setName(""); // NOI18N
        tfFatherLastname.setPreferredSize(new java.awt.Dimension(250, 36));
        getContentPane().add(tfFatherLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 210, -1));

        jLabel7.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel7.setText("Mother's last name  ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        tfMotherLastname.setBackground(new java.awt.Color(6, 6, 6));
        tfMotherLastname.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfMotherLastname.setForeground(new java.awt.Color(255, 255, 255));
        tfMotherLastname.setToolTipText("");
        tfMotherLastname.setBorder(null);
        tfMotherLastname.setName(""); // NOI18N
        tfMotherLastname.setPreferredSize(new java.awt.Dimension(250, 36));
        getContentPane().add(tfMotherLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 220, -1));

        jLabel6.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel6.setText("Phone number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));

        tfPhoneNumber.setBackground(new java.awt.Color(6, 6, 6));
        tfPhoneNumber.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        tfPhoneNumber.setToolTipText("");
        tfPhoneNumber.setBorder(null);
        tfPhoneNumber.setName(""); // NOI18N
        tfPhoneNumber.setPreferredSize(new java.awt.Dimension(250, 36));
        getContentPane().add(tfPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 220, -1));

        jLabel12.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel12.setText("Estate");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        cmbEstate.setBackground(new java.awt.Color(6, 6, 6));
        cmbEstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEstate.setPreferredSize(new java.awt.Dimension(72, 36));
        getContentPane().add(cmbEstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 220, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 480, 30));

        jLabel13.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel13.setText("Monetary penalty");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 170, -1));

        tfMonetaryPenalty.setBackground(new java.awt.Color(6, 6, 6));
        tfMonetaryPenalty.setFont(new java.awt.Font("Poppins ExtraLight", 0, 14)); // NOI18N
        tfMonetaryPenalty.setForeground(new java.awt.Color(255, 255, 255));
        tfMonetaryPenalty.setToolTipText("");
        tfMonetaryPenalty.setBorder(null);
        tfMonetaryPenalty.setName(""); // NOI18N
        tfMonetaryPenalty.setPreferredSize(new java.awt.Dimension(250, 36));
        getContentPane().add(tfMonetaryPenalty, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 220, -1));

        jMenu1.setText("Generate");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DownloadReport_Icon.png"))); // NOI18N
        jMenuItem1.setText("Report");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDelete;
    private javax.swing.JLabel btnSearch;
    public javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbEstate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable tblClient;
    public javax.swing.JTextField tfDomicile1;
    public javax.swing.JTextField tfFatherLastname;
    public javax.swing.JTextField tfMonetaryPenalty;
    public javax.swing.JTextField tfMotherLastname;
    public javax.swing.JTextField tfName;
    public javax.swing.JTextField tfPhoneNumber;
    public javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
